name: Terraform destroy 

on:
  workflow_dispatch:
    branches:
      - main
    inputs:
      AWS_ACCESS_KEY_ID:
        description: 'AWS ACCESS KEY ID'
        required: true
      AWS_SECRET_ACCESS_KEY:
        description: 'AWS SECRET ACCESS KEY'
        required: true
      AWS_SESSION_TOKEN:
        description: 'AWS SESSION TOKEN'
        required: true
jobs:
  terraform-actions:
    name: Workflow destroy
    runs-on: ubuntu-latest
    steps:
    - name: Checkout Repository
      uses: actions/checkout@v1
    - name: Configure AWS Credentials
      uses: aws-actions/configure-aws-credentials@v1
      with:
        aws-access-key-id: ${{ github.event.inputs.AWS_ACCESS_KEY_ID }}
        aws-secret-access-key: ${{ github.event.inputs.AWS_SECRET_ACCESS_KEY }}
        aws-session-token: ${{ github.event.inputs.AWS_SESSION_TOKEN }}
        aws-region: ${{ secrets.AWS_REGION }} 
    - name: Install Terraform
      uses: hashicorp/setup-terraform@v1
    - name: Terraform fmt
      id: fmt
      run: terraform fmt
      continue-on-error: true
    - name: Terraform init 
      run: terraform  init -backend-config "bucket=${{ secrets.AWS_BUCKET_NAME }}" -backend-config "region=${{ secrets.AWS_REGION }}" -backend-config "key=${{ secrets.AWS_BUCKET_key }}"     
    - name: Terraform destroy AWS
      id: destroy_AWS
      run: terraform destroy -auto-approve -var "subnet_id=${{ secrets.SUBNET_ID }}" -var "security_group_id=${{ secrets.SECURITY_GROUP_ID }}"